export const DAO_ABI = [
  { type: 'error', name: 'AlreadyVoted', inputs: [] },
  { type: 'error', name: 'CallFail', inputs: [] },
  { type: 'error', name: 'InitCallFail', inputs: [] },
  { type: 'error', name: 'Initialized', inputs: [] },
  { type: 'error', name: 'InvalidNonce', inputs: [] },
  { type: 'error', name: 'InvalidSignature', inputs: [] },
  { type: 'error', name: 'NoArrayParity', inputs: [] },
  { type: 'error', name: 'NotCurrentProposal', inputs: [] },
  { type: 'error', name: 'NotDetermined', inputs: [] },
  { type: 'error', name: 'NotExtension', inputs: [] },
  { type: 'error', name: 'NotMember', inputs: [] },
  { type: 'error', name: 'NotProposer', inputs: [] },
  { type: 'error', name: 'NotVoteable', inputs: [] },
  { type: 'error', name: 'NullAddress', inputs: [] },
  { type: 'error', name: 'Overflow', inputs: [] },
  { type: 'error', name: 'Paused', inputs: [] },
  { type: 'error', name: 'PeriodBounds', inputs: [] },
  { type: 'error', name: 'PrevNotProcessed', inputs: [] },
  { type: 'error', name: 'QuorumMax', inputs: [] },
  { type: 'error', name: 'Reentrancy', inputs: [] },
  { type: 'error', name: 'SignatureExpired', inputs: [] },
  { type: 'error', name: 'Sponsored', inputs: [] },
  { type: 'error', name: 'SupermajorityBounds', inputs: [] },
  { type: 'error', name: 'TypeBounds', inputs: [] },
  { type: 'error', name: 'VotingNotEnded', inputs: [] },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { type: 'address', name: 'owner', internalType: 'address', indexed: true },
      { type: 'address', name: 'spender', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'amount', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DelegateChanged',
    inputs: [
      { type: 'address', name: 'delegator', internalType: 'address', indexed: true },
      { type: 'address', name: 'fromDelegate', internalType: 'address', indexed: true },
      { type: 'address', name: 'toDelegate', internalType: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DelegateVotesChanged',
    inputs: [
      { type: 'address', name: 'delegate', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'previousBalance', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'newBalance', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewProposal',
    inputs: [
      { type: 'address', name: 'proposer', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
      { type: 'uint8', name: 'proposalType', internalType: 'enum KaliDAO.ProposalType', indexed: true },
      { type: 'string', name: 'description', internalType: 'string', indexed: false },
      { type: 'address[]', name: 'accounts', internalType: 'address[]', indexed: false },
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]', indexed: false },
      { type: 'bytes[]', name: 'payloads', internalType: 'bytes[]', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauseFlipped',
    inputs: [{ type: 'bool', name: 'paused', internalType: 'bool', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalCancelled',
    inputs: [
      { type: 'address', name: 'proposer', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalProcessed',
    inputs: [
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
      { type: 'bool', name: 'didProposalPass', internalType: 'bool', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalSponsored',
    inputs: [
      { type: 'address', name: 'sponsor', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { type: 'address', name: 'from', internalType: 'address', indexed: true },
      { type: 'address', name: 'to', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'amount', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoteCast',
    inputs: [
      { type: 'address', name: 'voter', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
      { type: 'bool', name: 'approve', internalType: 'bool', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
    name: 'DOMAIN_SEPARATOR',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'allowance',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'approve',
    inputs: [
      { type: 'address', name: 'spender', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'balanceOf',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'burn',
    inputs: [{ type: 'uint256', name: 'amount', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'burnFrom',
    inputs: [
      { type: 'address', name: 'from', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'burnShares',
    inputs: [
      { type: 'address', name: 'from', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [
      { type: 'bool', name: 'mint', internalType: 'bool' },
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
    ],
    name: 'callExtension',
    inputs: [
      { type: 'address', name: 'extension', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
      { type: 'bytes', name: 'extensionData', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'cancelProposal',
    inputs: [{ type: 'uint256', name: 'proposal', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint32', name: 'fromTimestamp', internalType: 'uint32' },
      { type: 'uint112', name: 'votes', internalType: 'uint112' },
    ],
    name: 'checkpoints',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: 'didProposalPass', internalType: 'bool' }],
    name: 'countVotes',
    inputs: [
      { type: 'uint8', name: 'voteType', internalType: 'enum KaliDAO.VoteType' },
      { type: 'uint256', name: 'yesVotes', internalType: 'uint256' },
      { type: 'uint256', name: 'noVotes', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '', internalType: 'string' }],
    name: 'daoURI',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint8', name: '', internalType: 'uint8' }],
    name: 'decimals',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'delegate',
    inputs: [{ type: 'address', name: 'delegatee', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'delegateBySig',
    inputs: [
      { type: 'address', name: 'delegatee', internalType: 'address' },
      { type: 'uint256', name: 'nonce', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'delegates',
    inputs: [{ type: 'address', name: 'delegator', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '', internalType: 'string' }],
    name: 'docs',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'extensions',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getCurrentVotes',
    inputs: [{ type: 'address', name: 'account', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getPriorVotes',
    inputs: [
      { type: 'address', name: 'account', internalType: 'address' },
      { type: 'uint256', name: 'timestamp', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'address[]', name: 'accounts', internalType: 'address[]' },
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
      { type: 'bytes[]', name: 'payloads', internalType: 'bytes[]' },
    ],
    name: 'getProposalArrays',
    inputs: [{ type: 'uint256', name: 'proposal', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint64', name: '', internalType: 'uint64' }],
    name: 'gracePeriod',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'init',
    inputs: [
      { type: 'string', name: 'name_', internalType: 'string' },
      { type: 'string', name: 'symbol_', internalType: 'string' },
      { type: 'string', name: 'docs_', internalType: 'string' },
      { type: 'bool', name: 'paused_', internalType: 'bool' },
      { type: 'address[]', name: 'extensions_', internalType: 'address[]' },
      { type: 'bytes[]', name: 'extensionsData_', internalType: 'bytes[]' },
      { type: 'address[]', name: 'voters_', internalType: 'address[]' },
      { type: 'uint256[]', name: 'shares_', internalType: 'uint256[]' },
      { type: 'uint64[16]', name: 'govSettings_', internalType: 'uint64[16]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'lastYesVote',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'mintShares',
    inputs: [
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [{ type: 'bytes[]', name: 'results', internalType: 'bytes[]' }],
    name: 'multicall',
    inputs: [{ type: 'bytes[]', name: 'data', internalType: 'bytes[]' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '', internalType: 'string' }],
    name: 'name',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'nonces',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'numCheckpoints',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'bytes4', name: '', internalType: 'bytes4' }],
    name: 'onERC1155BatchReceived',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256[]', name: '', internalType: 'uint256[]' },
      { type: 'uint256[]', name: '', internalType: 'uint256[]' },
      { type: 'bytes', name: '', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'bytes4', name: '', internalType: 'bytes4' }],
    name: 'onERC1155Received',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'bytes', name: '', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'bytes4', name: '', internalType: 'bytes4' }],
    name: 'onERC721Received',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'bytes', name: '', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'paused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'permit',
    inputs: [
      { type: 'address', name: 'owner', internalType: 'address' },
      { type: 'address', name: 'spender', internalType: 'address' },
      { type: 'uint256', name: 'value', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [
      { type: 'bool', name: 'didProposalPass', internalType: 'bool' },
      { type: 'bytes[]', name: 'results', internalType: 'bytes[]' },
    ],
    name: 'processProposal',
    inputs: [{ type: 'uint256', name: 'proposal', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'proposalCount',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'bool', name: 'passed', internalType: 'bool' },
      { type: 'bool', name: 'processed', internalType: 'bool' },
    ],
    name: 'proposalStates',
    inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint8', name: '', internalType: 'enum KaliDAO.VoteType' }],
    name: 'proposalVoteTypes',
    inputs: [{ type: 'uint8', name: '', internalType: 'enum KaliDAO.ProposalType' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint8', name: 'proposalType', internalType: 'enum KaliDAO.ProposalType' },
      { type: 'string', name: 'description', internalType: 'string' },
      { type: 'uint256', name: 'prevProposal', internalType: 'uint256' },
      { type: 'uint112', name: 'yesVotes', internalType: 'uint112' },
      { type: 'uint112', name: 'noVotes', internalType: 'uint112' },
      { type: 'uint32', name: 'creationTime', internalType: 'uint32' },
      { type: 'address', name: 'proposer', internalType: 'address' },
    ],
    name: 'proposals',
    inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [{ type: 'uint256', name: 'proposal', internalType: 'uint256' }],
    name: 'propose',
    inputs: [
      { type: 'uint8', name: 'proposalType', internalType: 'enum KaliDAO.ProposalType' },
      { type: 'string', name: 'description', internalType: 'string' },
      { type: 'address[]', name: 'accounts', internalType: 'address[]' },
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
      { type: 'bytes[]', name: 'payloads', internalType: 'bytes[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint64', name: '', internalType: 'uint64' }],
    name: 'quorum',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [
      { type: 'bool', name: 'success', internalType: 'bool' },
      { type: 'bytes', name: 'result', internalType: 'bytes' },
    ],
    name: 'relay',
    inputs: [
      { type: 'address', name: 'account', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
      { type: 'bytes', name: 'payload', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'sponsorProposal',
    inputs: [{ type: 'uint256', name: 'proposal', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint64', name: '', internalType: 'uint64' }],
    name: 'supermajority',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'supportsInterface',
    inputs: [{ type: 'bytes4', name: 'interfaceId', internalType: 'bytes4' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '', internalType: 'string' }],
    name: 'symbol',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'totalSupply',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'transfer',
    inputs: [
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'transferFrom',
    inputs: [
      { type: 'address', name: 'from', internalType: 'address' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'vote',
    inputs: [
      { type: 'uint256', name: 'proposal', internalType: 'uint256' },
      { type: 'bool', name: 'approve', internalType: 'bool' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'voteBySig',
    inputs: [
      { type: 'address', name: 'signer', internalType: 'address' },
      { type: 'uint256', name: 'proposal', internalType: 'uint256' },
      { type: 'bool', name: 'approve', internalType: 'bool' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'voted',
    inputs: [
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'address', name: '', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint64', name: '', internalType: 'uint64' }],
    name: 'votingPeriod',
    inputs: [],
  },
  { type: 'receive', stateMutability: 'payable' },
] as const
