export const TRIBUTE_ABI = [
  { type: 'error', name: 'NotProcessed', inputs: [] },
  { type: 'error', name: 'NotProposal', inputs: [] },
  { type: 'error', name: 'NotProposer', inputs: [] },
  { type: 'error', name: 'Reentrancy', inputs: [] },
  { type: 'error', name: 'Sponsored', inputs: [] },
  {
    type: 'event',
    name: 'NewTributeProposal',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute', indexed: true },
      { type: 'address', name: 'proposer', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
      { type: 'address', name: 'asset', internalType: 'address', indexed: false },
      { type: 'bool', name: 'nft', internalType: 'bool', indexed: false },
      { type: 'uint256', name: 'value', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TributeProposalCancelled',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TributeProposalReleased',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute', indexed: true },
      { type: 'uint256', name: 'proposal', internalType: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'cancelTributeProposal',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute' },
      { type: 'uint256', name: 'proposal', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bytes[]', name: 'results', internalType: 'bytes[]' }],
    name: 'multicall',
    inputs: [{ type: 'bytes[]', name: 'data', internalType: 'bytes[]' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'releaseTributeProposal',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute' },
      { type: 'uint256', name: 'proposal', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'releaseTributeProposalAndProcess',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute' },
      { type: 'uint256', name: 'proposal', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'selfPermit',
    inputs: [
      { type: 'address', name: 'token', internalType: 'contract Permit' },
      { type: 'address', name: 'owner', internalType: 'address' },
      { type: 'uint256', name: 'value', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'selfPermit1155',
    inputs: [
      { type: 'address', name: 'token', internalType: 'contract Permit' },
      { type: 'address', name: 'owner', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'selfPermit721',
    inputs: [
      { type: 'address', name: 'token', internalType: 'contract Permit' },
      { type: 'uint256', name: 'tokenId', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'bytes', name: 'sig', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'selfPermit721',
    inputs: [
      { type: 'address', name: 'token', internalType: 'contract Permit' },
      { type: 'uint256', name: 'tokenId', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'selfPermitAllowed',
    inputs: [
      { type: 'address', name: 'token', internalType: 'contract Permit' },
      { type: 'address', name: 'owner', internalType: 'address' },
      { type: 'uint256', name: 'nonce', internalType: 'uint256' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    outputs: [],
    name: 'submitTributeProposal',
    inputs: [
      { type: 'address', name: 'dao', internalType: 'contract IKaliDAOtribute' },
      { type: 'uint8', name: 'proposalType', internalType: 'enum IKaliDAOtribute.ProposalType' },
      { type: 'string', name: 'description', internalType: 'string' },
      { type: 'address[]', name: 'accounts', internalType: 'address[]' },
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
      { type: 'bytes[]', name: 'payloads', internalType: 'bytes[]' },
      { type: 'bool', name: 'nft', internalType: 'bool' },
      { type: 'address', name: 'asset', internalType: 'address' },
      { type: 'uint256', name: 'value', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'address', name: 'proposer', internalType: 'address' },
      { type: 'address', name: 'asset', internalType: 'address' },
      { type: 'bool', name: 'nft', internalType: 'bool' },
      { type: 'uint256', name: 'value', internalType: 'uint256' },
    ],
    name: 'tributes',
    inputs: [
      { type: 'address', name: '', internalType: 'contract IKaliDAOtribute' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
  },
] as const
